#-------------------------------------------------------------------------
# TITLE: 
#    pkgIndex.tcl
#
# PROJECT:
#    atdict: Your project description
#
# DESCRIPTION:
#    atdict(n): pkgIndex file
#
#    Generated by Quill
#
#-------------------------------------------------------------------------

# -quill-ifneeded-begin DO NOT EDIT BY HAND
package ifneeded atdict 0.0a0 [list source [file join $dir pkgModules.tcl]]
# -quill-ifneeded-end
